### ISSUE TITLE
Error loading plugin

### ISSUE THREAD

**Issue by Breaveheard** [marcsowen/homebridge-homematicip#165] opened 2021-07-28 19:58 UTC
I do face the following error with a fresh homebridge installation on raspbian

![A50B6D64-8186-42B1-BBB2-61F53DDF955E](https://user-images.githubusercontent.com/6759133/127386847-e094c1c7-937a-499d-9c48-3aefdf09a218.png)
![76AA6B24-41DD-4D6D-A2F5-8216F0A738A0](https://user-images.githubusercontent.com/6759133/127386861-5fbd1277-cd07-4a85-b3df-bb30433c936d.png)
![7B6D9370-98B1-4AC6-8EF2-A9EB2F65B2BB](https://user-images.githubusercontent.com/6759133/127387556-4fd0351c-9efa-41fd-a79e-b22da17aeb59.jpeg)

**Comment by KGrunwa** [comment] 2021-07-29 07:49
Hey get the same .... My installation runs on a docker container.... fresh installation same error...tryed a lot but always the same issue.
Hope we get a fix.....

**Comment by marcsowen** [comment] 2021-07-29 09:45
This is an issue with newer versions of node-fetch. See:

https://github.com/node-fetch/node-fetch/issues/1226

I'll try to fix that.

**Comment by KGrunwa** [comment] 2021-07-29 10:00
That would be awesome !!

Many many thanks !!!

Greetings 

Von meinem iPhone gesendet

**Comment by marcsowen** [comment] 2021-07-29 10:07
I have released version 0.5.1 which is forcing the old node-fetch version until the issue is fixed on node-fetch side. Can you try if this works? Be sure that version 0.5.1 of homebridge-homematicip is displayed while loading.

**Comment by KGrunwa** [comment] 2021-07-29 10:43
Hey Marc,

 

now i can tell ya it works but with some litte issues…. But at this time it works….

 

Device not implemented: HMIP-WRC2 - Wandtaster via type PUSH_BUTTON
Device not implemented: HmIP-WRC6 - Wandtaster - 6-fach via type PUSH_BUTTON_6

Device not implemented: HmIP-HAP - HOME_CONTROL_ACCESS_POINT via type HOME_CONTROL_ACCESS_POINT

This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 5 exceeded minimum of 10.

 

 

Maybe you could have a look about that little things ???

 

 

Many many thanks to bring ya plugin up and running !!!

 

 

Von: Marc Sowen ***@***.***> 
Gesendet: Donnerstag, 29. Juli 2021 12:08
An: marcsowen/homebridge-homematicip ***@***.***>
Cc: KGrunwa ***@***.***>; Comment ***@***.***>
Betreff: Re: [marcsowen/homebridge-homematicip] Error loading plugin (#165)

 

I have released version 0.5.1 which is forcing the old node-fetch version until the issue is fixed on node-fetch side. Can you try if this works? Be sure that version 0.5.1 of homebridge-homematicip is displayed while loading.

**Comment by marcsowen** [comment] 2021-07-29 11:06
Hi,

> Device not implemented: HMIP-WRC2 - Wandtaster via type PUSH_BUTTON
> Device not implemented: HmIP-WRC6 - Wandtaster - 6-fach via type PUSH_BUTTON_6
> Device not implemented: HmIP-HAP - HOME_CONTROL_ACCESS_POINT via type HOME_CONTROL_ACCESS_POINT

These warnings are perfectly normal. They are not supported as separate HomeKit-Devices. This seems like a bug especially for HOME_CONTROL_ACCESS_POINT, but it just means that you cannot see this a device you can control in your Home app. Of course the access point is used anyway to transmit the commands.

> This plugin generated a warning from the characteristic 'Target Temperature': characteristic was supplied illegal value: number 5 exceeded minimum of 10.

Also just a warning. The HomeKit-Library I use warns if numbers are out of range. Actually it seems a little odd, that you want to set the target temperature below 10 degrees celsius. Most devices won't accept temperatures lower than ~16 degrees. Where did you set it?

Everything probably runs just fine. Just ignore the warnings. :)

**Comment by KGrunwa** [comment] 2021-07-29 11:37
Hey Marc

Great to hear that I can ignore the warnings….

Also just a warning. The HomeKit-Library I use warns if numbers are out of range. Actually it seems a little odd, that you want to set the target temperature below 10 degrees celsius. Most devices won't accept temperatures lower than ~16 degrees. Where did you set it?

I set the 5degree in the homematic ip app … it’s the lowest definition and means „off“ I think….

Many thanks for your help !!!

Greetings 


Von meinem iPhone gesendet

> Am 29.07.2021 um 13:06 schrieb Marc Sowen ***@***.***>:
> 
> Also just a warning. The HomeKit-Library I use warns if numbers are out of range. Actually it seems a little odd, that you want to set the target temperature below 10 degrees celsius. Most devices won't accept temperatures lower than ~16 degrees. Where did you set it?

**Closed** 2021-09-22 09:36 UTC
