### ISSUE TITLE
Not working with Hoobs4

### ISSUE THREAD

**Issue by lion33319** [marcsowen/homebridge-homematicip#180] opened 2021-08-15 06:54 UTC
Hi,
Love the Plugin… but unfortunately it seems that it is completely not working anymore with hoobs4.
I updated to the latest Hoobs version (4.0.100) and the homematic Plugin can’t be configured at all anymore.
I can hit the configure button and it shows me a terminal Input. When I input the info (e.g. the SGTIN number from the Access Point) and restart the Bridge nothing happens.
The bridge not seem to recognize the plug-in at all. The bridge loads all other plug-ins but the log does not ask to „press the access point button“. There seems to be an issue with the plug-in and hoobs4.
Any info on solving this issue?

**Comment by steckenpferd** [comment] 2021-08-24 07:15
I recommend to open a ticket also at Hoobs - let's see if they have maybe an information why is it now working with their latest software

**Comment by decodrr** [comment] 2021-09-19 19:51
@lion33319 , did you find a way to solve your problem? I don't want to upgrade to HOOBS 4 until I know that it works with Homematic IP. Thank you!

**Comment by lion33319** [comment] 2021-09-19 20:15
Unfortunately not. I had to downgrade back to 3.3.12 (pain in the…).
Now homematic works again. I won’t be upgrading until someone definitely comments that this works 😒

**Comment by decodrr** [comment] 2021-09-20 11:35
@lion33319 , thank you for the heads-up! I will have to wait with upgrading to HOOBS 4 until @marcsowen adopted the homematic-ip plugin for the latest version.

**Comment by marcsowen** [comment] 2021-09-22 09:35
Unfortunately I don't have Hoobs. Is it possible for you to copy the startup sequence logs for the plugin from Hoobs?

**Comment by marcsowen** [comment] 2021-10-07 13:29
Can you try version 0.5.2? Is it possible to get some logging information from Hoobs?

**Comment by FalkSoft** [comment] 2021-10-09 12:47
Hello, I installed the version 0.5.2 on Hoobs4 Version 4.0.18.0 and I have the same issue.
9.10.2021, 13:50:09Homematicip BridgeConfiguration change
9.10.2021, 13:50:09homematicipbridge stopping
9.10.2021, 13:50:14Homematicip Bridge starting
9.10.2021, 13:50:22Homematicip BridgeWARNUNGNo plugins installed.
9.10.2021, 13:50:22Homematicip BridgeLoading 1 platforms...
9.10.2021, 13:50:22Homematicip BridgeBridge is running on port 51846.

Config is 
{
    "platform": "HomematicIP",
    "name": "HomematicIP",
    "access_point": "3014-F711-A000-03DD-XXXX-XXXX",
    "pin": "XXX"
}

**Comment by ScharV** [comment] 2021-10-09 18:13
Hey guys short information, the issue is that Hoobs 4 uses port 9090 as well as the Plugin.

**Comment by decodrr** [comment] 2021-10-11 18:39
> Hey guys short information, the issue is that Hoobs 4 uses port 9090 as well as the Plugin.

Hi, is this a new feature? I found the following on the Hoobs website: 

TERMINAL
The terminal is available in the UI for more advanced operations.
The terminal is powered by HelM. The terminal can also be accessed from the device’s URL on port 9090, even if the HOOBS™ server is unable to start.

What is the best way to resolve this port conflict?

**Comment by marcsowen** [comment] 2021-10-12 06:45
I'm actually not aware the homematicip plugin is using any port other than the ones homebridge need to communicate with the other iOS devices in the house. HomematicIP is just actively connecting to the HmIP-cloud using basic https connection using a port defined by the HmIP-cloud (currently port 6969)  and another active connection to a HmIP websocket using another cloud defined port (currently port 8888). But the plugin is not listening to any port at all - it just doesn't need to.

@ScharV What is the exact setting to reconfigure homebridge-homematic to use a different port?

**Comment by lurid-bogey** [comment] 2021-10-30 19:37
Unfortunately I’m affected by this bug too 😭
My Hoobs box got force-upgraded to version 4 and now the HomematicIP plugin is not working anymore.
I’ll try to downgrade to version 3, but I’m not sure if that’s possible at all.

**Comment by ahstax** [comment] 2021-10-31 08:05
As I learned recently there is an other repository called „Homematicip Svenlie Bridge“, which works with my hoobs.

i do not know the difference. In fact, the programmer seams to be the same.

**Comment by lurid-bogey** [comment] 2021-10-31 09:48
I just tried the „Homematicip Svenlie Bridge“, but it’s not working for me either.

@ahstax: How did you make it work? What is your config?

**Comment by ahstax** [comment] 2021-11-02 09:06
Hi,
I used an empty config and added this:
{
    "platform": "HomematicIP",
    "name": "HomematicIP",
    "access_point": "<your access point ID without blancs or dashes or the like>",
    "pin": "<your PIN if set in the app>"
}
in the Log-view I then waited until I've been asked to press the blue button on my AccessPoint. Afterwards I've been provided with an authcode.
I took this authcode and replaced the forestanding code in complete with
{
    "platform": "HomematicIP",
    "name": "HomematicIP",
    "access_point": "<your access point ID without blancs or dashes or the like>",
    "auth_token": "<your API auth token without blancs or dashes or the like>"
}

This worked for me...

**Comment by lurid-bogey** [comment] 2021-11-16 19:36
Thanks for your help, but the workarounds are not working for me. 
I downgraded my Hoobs to version 3 and everything is working fine again.

**Comment by FalkSoft** [comment] 2021-11-18 13:07
HomematicIP now works for me with Hoobs4!!
There were several problems with me. 
My Hoobs4 could not be updated and was stuck at 4.0.109. Some others probably had this problem and there was in the Hoobs forum to update the info Hoobs4 as follows **curl -sk https://dl.hoobs.org/fix | sudo bash -** (so my Hoobs4 was updated from 4.0.109 to 4.1.15).
After that, everything looked a little better, but unfortunately HomematicIP still didn't work after that. 
I have not received any information to receive the auth key via blue button. 
I then reset my Hoobs4 (4.1.15) to factory settings and completely reinstalled HomematicIP (no backup - complete new).

Surprise after that everything worked suddenly as in the description of Marc: it came the request blue key -> Auth Key -> entered in config, runs!!!

![image](https://user-images.githubusercontent.com/92214354/142419563-02fe126d-432e-4aea-872f-d710b2574f99.png)
![image](https://user-images.githubusercontent.com/92214354/142419655-1fadf443-0f85-4218-800f-916bfe5cc14a.png)
![image](https://user-images.githubusercontent.com/92214354/142419736-81d84165-6787-4690-b20d-7b1576900abd.png)
![image](https://user-images.githubusercontent.com/92214354/142419812-2772ac48-1447-4404-816d-386beaf8c99a.png)

Now all works fine for me :)

**Comment by decodrr** [comment] 2021-11-19 11:26
Still not working for me :-(

- I updated to HOOBS 4.1.15, Node 14.18.1 and Homebridge 1.3.5
- I did a factory reset of HOOBS
- I installed Homematicip 0.5.2
- I removed the bridge from HomeKit
- I deleted the "user" HOOBS in the HomematicIP app  
- I configured Homematicip with the following configuration:

{
    "platform": "Homematicip",
    "name": "HomematicIP",
    "access_point": "3014-F711-A000-03DB-E98D-####",
    "pin": "1234"
}

However, I do not get any prompt in the "Log" to press the blue button or any auth_code message.

How can I get the auth_code?

Thank you!

**Comment by FalkSoft** [comment] 2021-11-19 11:41
IP in large letters

{
"platform": "Homematic**IP**",  IP in large letters
"name": "HomematicIP",
"access_point": "3014-F711-A000-03DB-E98D-####",
"pin": "1234"
}

and copy it directly into the advanced tab of HomematicIP (not into the normal homematicip tab)

There is an issue if you use the normal homaticuip tab

**Comment by decodrr** [comment] 2021-11-19 12:05
Thank you @FalkSoft for the quick reply!

First of all, I got it working now! 🥳

However, I had to make additional changes:

1. You were right that "IP" needed to be written with capital letters. This should be considered as a bug since this is the default entry after installing the plugin. 
2. My situation is a little more complex because I have two HMIP-HAPs for [advanced routing](https://www.youtube.com/watch?v=8-ykhApE-ag). It turned out that the HAPs are not the same, even if you unplug the second HAP completely and are only working with the HAP with the dark blue light. I had to "fail over" all devices to my "original" HAP and unplug the "new" HAP and also use the SGTIN from the "original" HAP. 

Next I will have to manually re-assign all HMIP devices to the HomeKit rooms which will take some time. 

I hope this process will become more convenient in the future. 

Good luck everyone with your personal setup!

**Comment by ahstax** [comment] 2021-11-19 15:39
**OK, thats it! :-D**

Does one accidentally know, what this means and how it is solvable?
`IMPORTANT !! Starting this version, your homematic custom configuration is located in /var/lib/hoobs/homematicbridgeccu3/homematic_config.json
unhandled rejection: RangeError [ERR_SOCKET_BAD_PORT]: options.port should be >= 0 and < 65536. Received 80803.`
https://github.com/thkl/homebridge-homematic

**Comment by marcsowen** [comment] 2021-11-22 17:06
@FalkSoft Good catch! Thanks a lot. That's a problem I didn't see coming when starting to develop the plugin. The name of the plugin is indeed "homematicip" where as the platform name is "HomematicIP". Seems like Hoobs tries to guess the platform name from the plugin name. Sorry for the confusion.

I will probably leave it as is though because it might break working installations for everyone else.

**Comment by marcsowen** [comment] 2021-12-02 11:25
Are there still any problems left? If not, I will close the issue.

**Comment by FalkSoft** [comment] 2021-12-02 12:57
@marcsowen From my point of view, all looks fine know and works with Hoobs 4

**Closed** 2021-12-14 08:54 UTC
Labels: bug
